### ISSUE TITLE
Uncompress Zip

### ISSUE THREAD

**Issue by alcides** [alcides/wallmanager#1]
Create signal on post_save of Application instances to uncompress the application zip.

**Comment by sdsantos** [comment]
After the uncompression there should be also some sort of integrity check of the application. Something like checking if there is a boot.bat or not. This way we can notify the user that uploaded the application of that sort of error instantaneously.

**Comment by alcides** [comment]
Nop, the uncompressing of the zip should be made asynchronously. What we could do is to check if the zip is not valid, email the author.

**Comment by sdsantos** [comment]
That's a shame, an instant error message would be great.

**Comment by sdsantos** [comment]
Closing this issue, since its a todo.
