### ISSUE TITLE
Upload a zip file

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#10]
The system accepts empty zip files, another kind of files but with a .zip extension, and without the correct application format.

VERSION 14-April 17:00

REPRODUCTION:
1 - Add application page or edit application page
2 - Make one of the three actions mentioned above, related with the zip file
3 - Click on button "Save"
4 - The system accepts the zip file

**Comment by alcides** [comment]
Caso o zip não funcione, ele vai receber um email a dizer que não foi possível fazer a descompressão.

Deverá existir também a verificação da existência do boot.bat

**Comment by alcides** [comment]
ASSIGNED_TO: Miguel Martins

**Comment by alcides** [comment]
ASSIGNED_TO: Alcides Fonseca

THREATED: Quando não consegue extrair, ou não existe o boot.bat, ele manda mail a avisar, apaga a aplicação e apaga do disco.

FIXED IN VERSION:  db3833c868a410808f2dd862039b58254d7b9333

**Comment by ghost** [comment]
The web application continues to accept:
- empty zip files (system test number 03.03)
- another kind of files but with a .zip extension (system test number 03.05)
- zip files without the correct application format (system test number 03.06)

Ok, it is supposed to accept and send an email to the author with info about the error in the deploy process.

But the problem is that these files aren't removed from the Sense Wall as soon as they are extracted. Then, when a web user tries to launch these files, it could happen nothing or it can cause a freeze on the Sense Wall..
