### ISSUE TITLE
The administrator cannot delete any application

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#11]
The administrator cannot see the "Delete application" link on any application in the system.

VERSION 14-April 17:00

REPRODUCTION:
1 - Applications page
2 - Click on any application
3 - There is no "Delete application" link on the application

**Comment by joaor** [comment]
ASSIGNED TO: João Rodrigues

**Comment by joaor** [comment]
TREATED:

The if statement to allow the admin access the remove button was missing. 

FIXED IN VERSION: 1.1

**Comment by joaor** [comment]
FIXED IN VERSION: b084cc739dda4539e8d4fad68a542cafb42002a4
