### ISSUE TITLE
Sometimes, the web user cannot delete an application

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#12]
After the web user confirms that he wants to delete an application, the applications page still shows that application.
At the second try, the application is deleted.

VERSION 14-April 17:00

REPRODUCTION:
1 - Applications page
2 - Select the application to delete
3 - Confirm the deletion
4 - The application is not deleted

**Comment by alcides** [comment]
This is a known limitation. I believe it has to do with the fact that the application is not extracted yet.

A possible solution would be to only show the delete button when the app is fully extracted. However if it goes wrong, it should be removed or disabled.

**Comment by joaope** [comment]
On application's page, and while is_extracted equals to False, it can be showed an information bar with something like "Application's submission is being processed..." and disable or hidden those "Edit" and "Delete" options

**Comment by alcides** [comment]
ASSIGNED_TO: Miguel Bento

**Comment by alcides** [comment]
ASSIGNED_TO: André

Incluí isto nas mensagens.

**Comment by alcides** [comment]
ASSIGNED_TO: Sérgio Santos

**Comment by sdsantos** [comment]
Resolved. Encontra-se agora no master.
