### ISSUE TITLE
Crash when a category is being edited, but it is deleted in another window

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#13]
The administrator starts editing a category, but he deletes it in another window, and then tries to submit his edition.
The system doesn't detect that the category has been deleted.

VERSION 29-April 23:00

REPRODUCTION:
1 - Edit category page
2 - Starts editing the category
3 - Open a second window and remove the category
4 - Return to first window, and try to submit the edition
5 - The system doesn't detect that the category has been deleted

**Comment by alcides** [comment]
THREATED: Feito o mesmo que às aplicações.

No entanto duvido que isto seja considerado um crash, simplesmente não detectou algo.

FIXED IN VERSION 8a2df92f9f8b36215e8b3c55bbb5a4c3bd416096
