### ISSUE TITLE
Report Abuse - hide the field Abuse Description 

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#14]
VERSION 29-April 23:00

REPRODUCTION:
1 - "Applications List" page
2 - Click on any application
3 - Click on the "Report Abuse" link
4 - Click again on the "Report Abuse" link
5 - The system doesn't hide the field Abuse Description

**Comment by alcides** [comment]
ASSIGNED_TO: Miguel Martins

**Comment by miguelmartins1987** [comment]
TREATED: Eram só umas linhas de código no application_detail.html. Basicamente, era só verificar o atributo visibility da form e alterá-lo.

FIXED IN VERSION: ee1409e3cd60d1c86e30137398d9259ab0b88ef5
