### ISSUE TITLE
The web user doesn't fill the field Abuse Description

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#15]
VERSION 29-April 23:00

REPRODUCTION:
1 - "Applications List" page
2 - Click on any application
3 - Click on the "Report Abuse" link
4 - The web user doesn't fill the field Abuse Description
5 - The system accepts the input

**Comment by alcides** [comment]
ASSIGNED: Miguel Martins

**Comment by alcides** [comment]
THREATED: Link url fixed.

FIXED IN VERSION: 10d8e428699f7f8bc5378dd0919f0f4f56a763f5

**Comment by ghost** [comment]
I verified that the web application shows the message "This field is required" and the email is not sent, but it presents the label "Application tic tac toe reported successfully." when the web user doesn't fill the field Abuse Description.

In this case, the label should be removed and when the web user fills the field Abuse Description, because there is already the label "Your report was sent successfully."

**Comment by miguelmartins1987** [comment]
TREATED: Message moved to the correct place.

FIXED IN VERSION: 26619fe141ea676a5387daaada7f008ef947a87c
