### ISSUE TITLE
Edit application accepts another kind of image, but with a .ico extension

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#16]
VERSION 29-April 23:00

REPRODUCTION:
1 - "Edit application" page
2 - The web user selects another kind of image, but with a .ico extension
3 - Click on the "Save" button
4 - The system accepts that file

**Comment by alcides** [comment]
Sorry, não percebi bem o erro, podias explicar um bocadinho?

**Comment by ghost** [comment]
Estou a assumir que o sistema só aceita como ícones, ficheiros com uma extensão .ico e que sejam mesmo ícones.
Por exemplo, um pdf com extensão .ico não deve ser aceite pelo sistema.
Isso está implementado na página "Add application" e surge uma mensagem de alerta, mas não na página "Edit application"

**Comment by alcides** [comment]
Ah já percebi o que querias dizer! E isto é culpa do nuno lourenço, que mudou o código porque não tinha uma biblioteca instalada.

Só para esclarecer uma cena: A extensão suposta é PNG e não ICO.

**Comment by alcides** [comment]
ASSIGNED_TO: Nuno Lourenço

Volta a meter o ImageField em vez do FileField no Edit for da Application.

**Comment by nunolourenco** [comment]
Eu fiz isso localmente, no meu pc, nunca fiz Push. Portanto isso já está assim a bastante tempo :O. Mas posso corrigir na boa :). As coisas que altero no meu pc nunca submeto para o git

**Comment by nunolourenco** [comment]
FIXED in : 3fcdf49a319febb06dfb
