### ISSUE TITLE
Sometimes, the Sense Wall crashes when an application is launched

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#17]
VERSION 06-May 15:00

REPRODUCTION:
1 - The SenseWall is active and none application is running
2 - The wall user single clicks on the application icon and then clicks on the button "Ok", or double clicks on the application icon
3 - The system crashes, and the machine must be rebooted

**Comment by disbeat** [comment]
ASSIGNED: msimoes

**Comment by disbeat** [comment]
TREATED: Several corrections on the booting of an application and the context switch between windows

FIXED IN VERSION: <a href="http://github.com/alcides/wallmanager/commit/e1a1bd4d8cec6429151396870928624726595d4b"> e1a1bd4d</a>
