### ISSUE TITLE
The wallpaper doesn't expand if the applications list is long

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#18]
VERSION 12-May 11:00

REPRODUCTION
1 - Login in the web application
2 - Applications list with more than 7 or 8 items
3 - The wallpaper doesn't expand

**Comment by ghost** [comment]
This issue is already resolved ?
So, put the ASSIGNED_TO, TREATED, FIXED IN VERSION references and the st_resolved tag and then I will close it.

**Comment by alcides** [comment]
THREATED: Fixed CSS

FIXED IN VERSION: e595692b66255493d9fc3dd5a83077ac6a45c7dd
