### ISSUE TITLE
The system doesn't show the last 3 execution logs

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#19]
VERSION 19-May 17:00

REPRODUCTION
1 - Applications list
2 - Select an application that belongs to the web user
3 - "Application log" link
4 - The system shows all the execution logs, instead of the last three ordered from the most recent launch

**Comment by alcides** [comment]
ASSIGNED TO: André

**Comment by andre99** [comment]
Sory, nem sabia que isso era um requisito :)

**Comment by andre99** [comment]
THREATED: Ordeno a lista e depois apanho os 3 mais recentes 

VERSION: b_issue19

**Comment by joaope** [comment]
O problema não está em **mostrar** todos os logs. Mostrando os 3 mais recentes estás a esconder o problema que é ele **guardar** todos os logs em vez de apenas os 3 últimos.

O signal post_save (função remove_extra_logs) não está a ser chamado, esse é o verdadeiro problema. Penso que deverá ser porque isto está do lado da wall e o django não se está a dar bem com Proxy=true e signals ao mesmo tempo.

Inicialmente pensei que fosse porque do lado da wall nós não usamos .save() mas mesmo adicionando isto o signal não é triggado.

Das duas uma:
1) Ou vocês percebem porque é que um model proxy não chama os signals
2) Fazem override do método save(), como vocês têm em vários modelos, em vez de signals.

PS: Encontrei este ticket do django: http://code.djangoproject.com/ticket/10672 Está marcado como fixed mas, ou estou a fazer alguma coisa mal, ou aqui não fixou nada!

PS2: Ainda me hão-de explicar porque têm signals para umas coisas e overrides de saves() para outras!!

**Comment by andre99** [comment]
Pah  o que diz aqui é que o sistema, no log, mostra mais que os últimos 3 logs, não fala nada em gravar.

No entanto para fazer o que estás a falar devias meter uma verificação quando guardas, ou algo do género.

Para mim o que eles reportaram está resolvido.

**Comment by joaope** [comment]
Essa verificação existe, e não está a funcionar. Esse é o bug.

Realmente este issue está mal escrito porque o sistema efectivamente mostra os 3 últimos logs. O problema é que mostra mais do que esses 3.

Com o problema de fundo resolvido a tua correcção torna-se obsoleta e por isso é que eu trouxe isto para este issue, por me parece o sítio indicado para o resolver e evitar trazer outro issue à baila.

Your call!

**Comment by andre99** [comment]
O problema é que a setting estava para 3 :P
Confirmem por favor :P

**Comment by ghost** [comment]
This issue isn't resolved yet..
It still shows just 3 execution logs, instead of 5
And it is not ordered from the most recent launch

**Comment by joaope** [comment]
Maybe because APPS_MAX_LOG_ENTRIES is setted to 3?

The order is not an issue.

**Comment by ghost** [comment]
I think it was decided in a recent meeting that should be presented 5 execution logs, instead of 3.
The order is not mandatory, I think that it was specified on the Requirements Document but it was not..

**Comment by alcides** [comment]
It is now ordered.
