### ISSUE TITLE
The contact administrator is removed from the system, but he continues to receive report abuse

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#20]
VERSION 26-May 14:00

REPRODUCTION:
1 - "Define Contact Admin" page
2 - Define the contact admin (for example: sdmart15@gmail.com)
3 - "Manage Admins" page
4 - Remove the administrator that is also defined as contact admin
5 - "Report Abuse" page
6 - Send a report abuse
7 - The contact admin continues to receive report abuse, after being removed from the system. It should appear the same message when the contact admin is not defined yet ("Unable to...")

**Comment by ghost** [comment]
The same happens for the "Contact Admin" page

**Comment by joaope** [comment]
Bug-fix commited

**Comment by alcides** [comment]
THREATED: Bug corrected

FIXED IN VERSION: f4453d4dd5b2ea249d9e409e801091748e4c8f47
