### ISSUE TITLE
The Sense Wall doesn't activate after 2 min of suspension

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#21]
VERSION 26-May 14:00

REPRODUCTION:
1 - "Projectors" page
2 - Define Inactivity time (example: 5 min)
3 - Wait for the suspension of the Sense Wall
4 - Wait 2 more minutes
5 - Try to activate the Sense Wall by touching the screen
6 - The Sense Wall doesn't activate

**Comment by alcides** [comment]
ASSIGNED_TO: Diogo Laginha

**Comment by laginha** [comment]
FIXED IN VERSION: <a href="http://github.com/alcides/wallmanager/commit/35cb07ff9ed8ee486e1e17601b051bb24390bf0e"> 35cb07ff </a>
