### ISSUE TITLE
Sometimes, an application isn't running on the wall, but the web application doesn't allow its edition or remotion

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#23]
VERSION 02-June 18:00

REPRODUCTION:
1 - Login as administrator
2 - Details page of an application
3 - "Delete Application" link
4 - The web application responds that the application is running on the wall, but is not..

There are several records on the Application entity of the database that the attribute is_running is true. Maybe, because when an application is ended that attribute for that application isn't changed to false. Or could be something else..

**Comment by laginha** [comment]
ASSIGNED TO: Diogo Laginha

**Comment by laginha** [comment]
FIXED IN VERSION: <a href="http://github.com/alcides/wallmanager/commit/35cb07ff9ed8ee486e1e17601b051bb24390bf0e"> 35cb07ff </a>
