### ISSUE TITLE
After sending an email to the defined contact admin, another page should be presented to the web user

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#24]
VERSION 02-June 18:00

REPRODUCTION:
1 - Contact Admin page
2 - Fill the field Message
3 - Click on the "Contact" button as many times as you want :)
4 - The defined contact admin receives the same amount of emails with the same message --> SPAM !

Suggestion: After clicking on the button "Contact" once, the web application should present other page to the web user. For example, Applications List page..

**Comment by andre99** [comment]
ASSIGNED_TO: André Lourenço

**Comment by andre99** [comment]
THREATED: adicionei um pseudo-redireccionamento para a lista de aplicações....

VERSION: b_issue_24
