### ISSUE TITLE
Unsuccessful e-mail test (after zip extraction)

### ISSUE THREAD

**Issue by miguelmartins1987** [alcides/wallmanager#4]
I apologize for violating the standard procedure, but this test hasn't been working for quite a while now, and I do not know what's wrong. I'm referring to the "test_email_after_zip_extraction" test on the "f_email_when_uploaded" branch. Please take a look at it.

**Comment by alcides** [comment]
E porque raio registaste um bug para uma coisa que não sabes fazer?

Não pedes desculpa por um erro que fazes. Simplesmente não o fazes. É o tipo de coisa que envias por email para mim, ou para a equipa de desenvolvimento.
