### ISSUE TITLE
fields Filename and Description with a giant word

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#5]
In the add application page and edit application page, when the web user writes a giant word, the system accepts the input.

VERSION 14-April 17:00

REPRODUCTION:
1 - Add application page or edit application page
2 - Filename or Description with a giant word
3 - Click on button "Save"
4 - The giant word is presented on the screen

**Comment by alcides** [comment]
ASSIGNED_TO: Alcides

**Comment by alcides** [comment]
Podias explicar-me melhor o problema?

Foi decidido que o nome das aplicações podem ter 50 caracteres no máximo. Logo podes escrever uma palavra de no máximo 50 caracteres, o que não me causa grandes problemas.

**Comment by alcides** [comment]
TREATED: Adicionado limite de 25 caracteres na lista de aplicações, mas é possível ser adicionada uma aplicação com um nome até 50 caracteres.

FIXED IN VERSION: ed9f4431e2384134304ab7218a68c533d6a6cd21

**Comment by ghost** [comment]
O problema é que a aplicação estava a aceitar palavras com qualquer tamanho, nos campos Filename e Description.
Reparámos que o campo Filename tem um limite de 255 caracteres, mas o campo Description não tem limite, ou se tem é muito maior do que 255..
Quando se submetia a aplicação, essa palavra enorme aparecia na lista de aplicações, o que estragava bastante a apresentação na janela.

**Comment by alcides** [comment]
Sim, o Description é para poderes escrever um texto longo a apresentar o teu projecto.
O filename houve uma discussão para decidir o tamanho.

Então se o problema é na lista, ficou resolvido com esse commit.
