### ISSUE TITLE
"Terms of service" box is not implemented

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#6]
In the add application page and edit application page, the "Terms of service" box is not implemented.

VERSION 14-April 17:00

REPRODUCTION:
1 - Add application page or edit application page
2 - There is no "Terms of service" box

**Comment by alcides** [comment]
ASSIGNED_TO: Alcides

**Comment by alcides** [comment]
TREATED: Added Terms of Service checkbox and validation.

A link will be added when the page is done.

FIXED IN VERSION: 3d4f58cba24421cb95476f35076a723f79806b79
