### ISSUE TITLE
"Filter" link and "Show only my applications" box don't exist

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#7]
In the applications page, the "Filter" link and the "Show only my applications" box don't exist, so the web user cannot search for the applications that belong to him.

VERSION 14-April 17:00

REPRODUCTION:
1 - Applications page
2 - There is no "Filter" link and "Search only my applications" box

**Comment by alcides** [comment]
This is part of a later use case: Search applications.

**Comment by alcides** [comment]
ASSIGNED_TO: Miguel Bento

**Comment by alcides** [comment]
ASSIGNED_TO: André Lourenço

**Comment by andre99** [comment]
Podem rever isto? é que o use case já está feito..... Têm de carregar no show...

**Comment by alcides** [comment]
Tens de responder aqui com o TREATED e FIXED IN VERSION hash_da_versao. Vê o quality assurance plan para veres como.

**Comment by alcides** [comment]
THREATED: Implementado caso de uso procurar e filtrar.

FIXED IN VERSION: 95bc0e560c3048bf0f8b4bc668630e6321daa62d
