### ISSUE TITLE
The system doesn't detect that the application has been removed

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#8]
The web user starts editing (or removing) an application, but he removes it in another window, and returns to the first window and tries to submit his edition (or remove the application).
The system doesn't detect that the application has been removed.

VERSION 14-April 17:00

REPRODUCTION:
1 - Edit application page or remove application page
2 - Starts editing (or removing) the application
3 - Open a second window and remove the application
4 - Return to first window, and try to submit the edition (or remove the application)
5 - The system doesn't detect that the application has been removed

**Comment by alcides** [comment]
ASSIGNED_TO: André

**Comment by andre99** [comment]
TREATED:  Added a verification before editing, that confirms that the application exist. in the case it doesn't exist it will send a message to the user.
FIXED IN VERSION: waiting for approval

**Comment by joaope** [comment]
Same verification is missing when removing application.

Taking the situation where multiple browser windows can be opened at the same time this kind of errors are prone to happen many times if verifications aren't implemented at all.

For example, and although "Manage Categories" isn't yet a concluded use case to be deeply tested, category_edit and category_remove both suffer from the same problem.
