### ISSUE TITLE
Crash when the web user doesn't upload any zip file

### ISSUE THREAD

**Issue by ghost** [alcides/wallmanager#9]
The system doesn't alert the web user, when he forgets to upload a zip file.

VERSION 14-April 17:00

REPRODUCTION:
1 - Add application page or edit application page
2 - The user doesn't select any zip file to upload
3 - Click on button "Save"
4 - The system crashes

**Comment by alcides** [comment]
ASSIGNED_TO: Alcides

**Comment by alcides** [comment]
TREATED: Made an extra validation
FIXED IN VERSION: f91877de6c5e34a9c5eca1973ddcf8c7c85e75cc
